### ISSUE TITLE
Django: add model "GoodHazardClass"

### ISSUE THREAD

**Issue by dra134102** [Gibb-Panda/collab-lodist-backend#12]
## Description
---
create the model "GoodHazardClass" in Django.

### Screenshots
<img width="466" alt="Screenshot 2024-03-27 at 4 18 52 PM" src="https://github.com/Gibb-Panda/collab-lodist/assets/154439939/be703053-9772-459e-8f56-22071ade7558">

**Comment by buechijonas** [comment]
Done by @jot005, the Profi Djangoler
